//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.proto
namespace common
{
    [global::ProtoBuf.ProtoContract(Name=@"Lang")]
    public enum Lang
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Russian", Value=1)]
      Russian = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"English", Value=2)]
      English = 2
    }
  
}