//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: profile.proto
// Note: requires additional types generated from: common.proto
namespace profile
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerProfile")]
  public partial class PlayerProfile : global::ProtoBuf.IExtensible
  {
    public PlayerProfile() {}
    
    private int _LastUnlockLevel = (int)3;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"LastUnlockLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)3)]
    public int LastUnlockLevel
    {
      get { return _LastUnlockLevel; }
      set { _LastUnlockLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}